config/routes.rb
Rails.application.routes.draw do
  resources :arrivals
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :properties
  resources :bookings
  resources :guests
  resources :cities
  resources :units
  resources :unit_types
  #get 'admin', to: 'admins#index'
  #get 'admin/:id', to: 'admins#show'
  #post 'admin/create', to: 'admins#create'
  #put 'admin/edit/:id', to: 'admins#update'
  #delete 'admin/:id', to: 'admins#delete'

  #get 'booking', to: 'bookings#index'
  #get 'booking/:id', to: 'bookings#show'
  #post 'booking/create', to: 'bookings#create'
  #put 'booking/edit/:id', to: 'bookings#update'
  #delete 'booking/:id', to: 'bookings#delete'

  #get 'guest', to: 'guests#index'
  #get 'guest/:id', to: 'guests#show'
  #post 'guest/create', to: 'guests#create'
  #put 'guest/edit/:id', to: 'guests#update'
  #delete 'guest/:id', to: 'guests#delete'

  #get 'property', to: 'properties#index'
  #get 'property/:id', to: 'properties#show'
  #post 'property/create', to: 'properties#create'
  #put 'property/edit/:id', to: 'properties#update'
  #delete 'property/:id', to: 'properties#delete'

  #get 'city', to: 'cities#index'
  #get 'city/:id', to: 'cities#show'
  #post 'cityt/create', to: 'cities#create'
  #put 'city/edit/:id', to: 'cities#update'
  #delete 'city/:id', to: 'cities#delete'

  #get 'unit', to: 'units#index'
  #get 'unit/:id', to: 'units#show'
  #post 'unit/create', to: 'units#create'
  #put 'unit/edit/:id', to: 'units#update'
  #delete 'unit/:id', to: 'units#delete'

  #get 'type', to: 'units#index'
  #get 'unit/:id', to: 'units#show'
  #post 'unit/create', to: 'units#create'
  #put 'unit/edit/:id', to: 'units#update'
  #delete 'unit/:id', to: 'units#delete'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrival.rb
class Arrival < ApplicationRecord
  belongs_to :guest
  belongs_to :unit
  belongs_to :status
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :city
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :property
  belongs_to :unit_type
end

app/models/unit_type.rb
class UnitType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/arrivals_controller.rb
class ArrivalsController < InheritedResources::Base

  private

    def arrival_params
      params.require(:arrival).permit(:guest_id, :unit_id, :checkin, :checkout, :status_id)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
end

app/controllers/guests_controller.rb
class GuestsController < InheritedResources::Base

  private

    def guest_params
      params.require(:guest).permit(:name, :email)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
end

app/controllers/unit_types_controller.rb
class UnitTypesController < ApplicationController
    before_action :set_unit_type, only: [ :show, :update, :delete ]

    def index
      @unit_types = UnitType.all
      render json: { result: true, unit_types: unit_types }, status: :ok
    end
      
    def show
      @unit_type = UnitType.find_by(id: params[:id])
	    render json: unit_type.nil? ? { data: "type not found"} : unit_type, status: :ok
    end
      
    def create
      unit_type = unit_type.create(unit_type_params)
      if unit_type.save
        render json: { result: true, unit_type: unit_type }, status: :created
      else
        render json: { result: false, unit_type: unit_type.errors }, status: :unprocessable_entity
      end
    end
      
    def update
      if @unit_type.update(unit_type_params)
        render json: { result: true, msg: "Update Success" }
      else  
        render json: { result: false, msg: "Update Failed" }
      end
    end
      
    def delete
      if @unit_type.destroy
        render json: { result: true, msg: "Delete Success" }
      else
        render json: { result: false, msg: "Delete Failed" }
      end
    end
      
    private

 
    def unit_type_params
      params.permit(:unit_type).require(:name)
    end
      
    def set_unit_type
      @unit_type = UnitType.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/unit_types_helper.rb
module UnitTypesHelper
end

app/views/arrivals/_form.html.erb
<%= form_with(model: arrival, local: true) do |form| %>
  <% if arrival.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arrival.errors.count, "error") %> prohibited this arrival from being saved:</h2>

      <ul>
      <% arrival.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guest_id %>
    <%= form.text_field :guest_id %>
  </div>

  <div class="field">
    <%= form.label :unit_id %>
    <%= form.text_field :unit_id %>
  </div>

  <div class="field">
    <%= form.label :checkin %>
    <%= form.date_select :checkin %>
  </div>

  <div class="field">
    <%= form.label :checkout %>
    <%= form.date_select :checkout %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.text_field :status_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arrivals/edit.html.erb
<h1>Editing Arrival</h1>

<%= render 'form', arrival: @arrival %>

<%= link_to 'Show', @arrival %> |
<%= link_to 'Back', arrivals_path %>

app/views/arrivals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arrivals</h1>

<table>
  <thead>
    <tr>
      <th>Guest</th>
      <th>Unit</th>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arrivals.each do |arrival| %>
      <tr>
        <td><%= arrival.guest %></td>
        <td><%= arrival.unit %></td>
        <td><%= arrival.checkin %></td>
        <td><%= arrival.checkout %></td>
        <td><%= arrival.status %></td>
        <td><%= link_to 'Show', arrival %></td>
        <td><%= link_to 'Edit', edit_arrival_path(arrival) %></td>
        <td><%= link_to 'Destroy', arrival, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arrival', new_arrival_path %>

app/views/arrivals/new.html.erb
<h1>New Arrival</h1>

<%= render 'form', arrival: @arrival %>

<%= link_to 'Back', arrivals_path %>

app/views/arrivals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guest:</strong>
  <%= @arrival.guest %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @arrival.unit %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @arrival.checkin %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @arrival.checkout %>
</p>

<p>
  <strong>Status:</strong>
  <%= @arrival.status %>
</p>

<%= link_to 'Edit', edit_arrival_path(@arrival) %> |
<%= link_to 'Back', arrivals_path %>

app/views/guests/_form.html.erb
<%= form_with(model: guest, local: true) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>